// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamechar.proto

package uk.ac.brighton.uni.ab607.mmorpg.test;

public final class GameCharacterProtoBuf {
  private GameCharacterProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameCharProtoBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 xy = 1;</code>
     */
    boolean hasXy();
    /**
     * <code>required int32 xy = 1;</code>
     */
    int getXy();

    /**
     * <code>required int32 spriteID = 2;</code>
     */
    boolean hasSpriteID();
    /**
     * <code>required int32 spriteID = 2;</code>
     */
    int getSpriteID();

    /**
     * <code>required int32 placedir = 3;</code>
     */
    boolean hasPlacedir();
    /**
     * <code>required int32 placedir = 3;</code>
     */
    int getPlacedir();

    /**
     * <code>required int32 ids = 4;</code>
     */
    boolean hasIds();
    /**
     * <code>required int32 ids = 4;</code>
     */
    int getIds();
  }
  /**
   * Protobuf type {@code uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf}
   */
  public static final class GameCharProtoBuf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf)
      GameCharProtoBufOrBuilder {
    // Use GameCharProtoBuf.newBuilder() to construct.
    private GameCharProtoBuf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameCharProtoBuf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameCharProtoBuf defaultInstance;
    public static GameCharProtoBuf getDefaultInstance() {
      return defaultInstance;
    }

    public GameCharProtoBuf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameCharProtoBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              xy_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              spriteID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              placedir_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ids_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.class, uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.Builder.class);
    }

    public static com.google.protobuf.Parser<GameCharProtoBuf> PARSER =
        new com.google.protobuf.AbstractParser<GameCharProtoBuf>() {
      public GameCharProtoBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameCharProtoBuf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameCharProtoBuf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int XY_FIELD_NUMBER = 1;
    private int xy_;
    /**
     * <code>required int32 xy = 1;</code>
     */
    public boolean hasXy() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 xy = 1;</code>
     */
    public int getXy() {
      return xy_;
    }

    public static final int SPRITEID_FIELD_NUMBER = 2;
    private int spriteID_;
    /**
     * <code>required int32 spriteID = 2;</code>
     */
    public boolean hasSpriteID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 spriteID = 2;</code>
     */
    public int getSpriteID() {
      return spriteID_;
    }

    public static final int PLACEDIR_FIELD_NUMBER = 3;
    private int placedir_;
    /**
     * <code>required int32 placedir = 3;</code>
     */
    public boolean hasPlacedir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 placedir = 3;</code>
     */
    public int getPlacedir() {
      return placedir_;
    }

    public static final int IDS_FIELD_NUMBER = 4;
    private int ids_;
    /**
     * <code>required int32 ids = 4;</code>
     */
    public boolean hasIds() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ids = 4;</code>
     */
    public int getIds() {
      return ids_;
    }

    private void initFields() {
      xy_ = 0;
      spriteID_ = 0;
      placedir_ = 0;
      ids_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasXy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpriteID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlacedir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIds()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, xy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, spriteID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, placedir_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ids_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, xy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, spriteID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, placedir_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ids_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf)
        uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.class, uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.Builder.class);
      }

      // Construct using uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        xy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        spriteID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        placedir_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ids_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor;
      }

      public uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf getDefaultInstanceForType() {
        return uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.getDefaultInstance();
      }

      public uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf build() {
        uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf buildPartial() {
        uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf result = new uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.xy_ = xy_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.spriteID_ = spriteID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.placedir_ = placedir_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ids_ = ids_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf) {
          return mergeFrom((uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf other) {
        if (other == uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf.getDefaultInstance()) return this;
        if (other.hasXy()) {
          setXy(other.getXy());
        }
        if (other.hasSpriteID()) {
          setSpriteID(other.getSpriteID());
        }
        if (other.hasPlacedir()) {
          setPlacedir(other.getPlacedir());
        }
        if (other.hasIds()) {
          setIds(other.getIds());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasXy()) {
          
          return false;
        }
        if (!hasSpriteID()) {
          
          return false;
        }
        if (!hasPlacedir()) {
          
          return false;
        }
        if (!hasIds()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.ac.brighton.uni.ab607.mmorpg.test.GameCharacterProtoBuf.GameCharProtoBuf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int xy_ ;
      /**
       * <code>required int32 xy = 1;</code>
       */
      public boolean hasXy() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 xy = 1;</code>
       */
      public int getXy() {
        return xy_;
      }
      /**
       * <code>required int32 xy = 1;</code>
       */
      public Builder setXy(int value) {
        bitField0_ |= 0x00000001;
        xy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xy = 1;</code>
       */
      public Builder clearXy() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xy_ = 0;
        onChanged();
        return this;
      }

      private int spriteID_ ;
      /**
       * <code>required int32 spriteID = 2;</code>
       */
      public boolean hasSpriteID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 spriteID = 2;</code>
       */
      public int getSpriteID() {
        return spriteID_;
      }
      /**
       * <code>required int32 spriteID = 2;</code>
       */
      public Builder setSpriteID(int value) {
        bitField0_ |= 0x00000002;
        spriteID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 spriteID = 2;</code>
       */
      public Builder clearSpriteID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        spriteID_ = 0;
        onChanged();
        return this;
      }

      private int placedir_ ;
      /**
       * <code>required int32 placedir = 3;</code>
       */
      public boolean hasPlacedir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 placedir = 3;</code>
       */
      public int getPlacedir() {
        return placedir_;
      }
      /**
       * <code>required int32 placedir = 3;</code>
       */
      public Builder setPlacedir(int value) {
        bitField0_ |= 0x00000004;
        placedir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 placedir = 3;</code>
       */
      public Builder clearPlacedir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        placedir_ = 0;
        onChanged();
        return this;
      }

      private int ids_ ;
      /**
       * <code>required int32 ids = 4;</code>
       */
      public boolean hasIds() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ids = 4;</code>
       */
      public int getIds() {
        return ids_;
      }
      /**
       * <code>required int32 ids = 4;</code>
       */
      public Builder setIds(int value) {
        bitField0_ |= 0x00000008;
        ids_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ids = 4;</code>
       */
      public Builder clearIds() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ids_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf)
    }

    static {
      defaultInstance = new GameCharProtoBuf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:uk.ac.brighton.uni.ab607.mmorpg.test.GameCharProtoBuf)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016gamechar.proto\022$uk.ac.brighton.uni.ab6" +
      "07.mmorpg.test\"O\n\020GameCharProtoBuf\022\n\n\002xy" +
      "\030\001 \002(\005\022\020\n\010spriteID\030\002 \002(\005\022\020\n\010placedir\030\003 \002" +
      "(\005\022\013\n\003ids\030\004 \002(\005B=\n$uk.ac.brighton.uni.ab" +
      "607.mmorpg.testB\025GameCharacterProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_uk_ac_brighton_uni_ab607_mmorpg_test_GameCharProtoBuf_descriptor,
        new java.lang.String[] { "Xy", "SpriteID", "Placedir", "Ids", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
